baseURL = "https://a1eksma.github.io/"
defaultContentLanguage = "ru"
theme = "congo"
enableRobotsTXT = true
enableGitInfo = true

[frontmatter]
  date = [":git", "date", "publishDate"]
  lastmod = [":git", "lastmod", "date"]

[permalinks]
  blog = "/blog/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
