languageCode = "ru"
languageName = "Русский"
weight = 1
title = "A1eksMa"

[params.author]
  name = "Alex Ma"
  image = "img/avatar.png"
  headline = "Unix Way · Python Zen · Data Driven"
  links = [
    { github = "https://github.com/A1eksMa" },
    { telegram = "https://t.me/a1ex_ma" },
    { discord = "https://discord.com/users/a1ex_ma" },
  ]
