languageCode = "en"
languageName = "English"
weight = 2
title = "A1eksMa"

[params.author]
  name = "Alex Ma"
  image = "img/avatar.png"
  headline = "Data Scientist · Data Engineer · Software Developer"
  links = [
    { github = "https://github.com/A1eksMa" },
    { telegram = "https://t.me/a1ex_ma" },
    { discord = "https://discord.com/users/a1ex_ma" },
  ]
